### PR TITLE
Remember scroll position when switching panels

### LINKED ISSUE #4: remember scroll
### Have you checked for existing feature requests?

- [X] Completed

### Summary

When you open the package details and then return to the package list the scroll position should be remembered. It may be the easiest to implement that the package you came from is shown.

### Enter your response below:

It would make it easier to search through packages because you wouldn't always start from the top.

### Any alternatives?

The current way is to always scroll through all packages. That is hard with a lot of packages.

### Other examples:

_No response_

### PR DESCRIPTION
**Pull request by jonian**
Remembers scroll position for all panels. Fixes #4.

### CODE REVIEW

**Review by confused-Techie — COMMENTED** [review]
This looks really good to me. Just want to make sure it works in every instance, would you mind cherry picking the latest commit to run CI on this PR?

**Comment by jonian** [comment]
Hi @confused-Techie, I don't understand what you want me to do, not that familiar with the project. Could you, please, explain further? Thanks!

**Comment by confused-Techie** [comment]
> Hi @confused-Techie, I don't understand what you want me to do, not that familiar with the project. Could you, please, explain further? Thanks!

Sure, I've just committed a PR that adds tests to this repo. And would like to run these tests on your PR, but your PR needs that latest commit. So using Git you can Cherry-pick the commit which will add it to your PR and run said tests. If that's something you're unfamiliar with let me know and I can do it for you or provide some documentation on the process.

**Comment by jonian** [comment]
Ok, now I understand. Isn't a rebase better in this case?

**Comment by confused-Techie** [comment]
> Ok, now I understand. Isn't a rebase better in this case?

That would work as well. Anything that gets said commit to your PR.

**Comment by jonian** [comment]
@confused-Techie rebased on master.

**Review by confused-Techie — APPROVED** [review]
Tests look good on this one with the expected failure rate. I'll allow some time for other reviewers but thanks for the contribution!

**Review by sertonix — APPROVED** [review]

**Pull request merged**
